image: haskell:8.6.5

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

stages:
  - build
  - test

cache:
  paths:
    - .stack-work/
    - .stack-root/

test:
  stage: test
  script:
    - ghc --version
    - stack --system-ghc build
    - stack test
