image: haskell:8.6.5

# variables:
#   STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

# cache:
#   paths:
#     - .stack-work/
#     - .stack-root/

test:
  script:
    # - ghc --version
    # - stack --system-ghc build
    - stack test
